export const AUDIT_ACTIONS = {
  // User Management (Admin)
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_SESSION_REVOKE: 'USER_SESSION_REVOKE',
  USER_2FA_ADMIN_RESET: 'USER_2FA_ADMIN_RESET',

  // Profile & Account
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',

  // Two-Factor Authentication
  TWO_FA_ENABLE_INIT: 'TWO_FA_ENABLE_INIT',
  TWO_FA_ENABLE_CONFIRM: 'TWO_FA_ENABLE_CONFIRM',
  TWO_FA_DISABLE: 'TWO_FA_DISABLE',

  // AI Agent
  AI_KEY_SAVE: 'AI_KEY_SAVE',
  AI_KEY_DELETE: 'AI_KEY_DELETE',
  AI_TOOL_CONFIRM: 'AI_TOOL_CONFIRM',
  AI_TOOLS_CONFIRM: 'AI_TOOLS_CONFIRM',

  // Cron Jobs
  CRON_JOB_CREATE: 'CRON_JOB_CREATE',
  CRON_JOB_DELETE: 'CRON_JOB_DELETE',
  CRON_JOB_TOGGLE: 'CRON_JOB_TOGGLE',
  CRON_JOB_RUN_MANUAL: 'CRON_JOB_RUN_MANUAL',

  // Log Drains
  LOG_DRAIN_CREATE: 'LOG_DRAIN_CREATE',
  LOG_DRAIN_UPDATE: 'LOG_DRAIN_UPDATE',
  LOG_DRAIN_DELETE: 'LOG_DRAIN_DELETE',

  // Vectors (pgvector)
  VECTOR_EXTENSION_ENABLE: 'VECTOR_EXTENSION_ENABLE',
  VECTOR_COLUMN_CREATE: 'VECTOR_COLUMN_CREATE',
  VECTOR_INDEX_CREATE: 'VECTOR_INDEX_CREATE',
  VECTOR_INDEX_DROP: 'VECTOR_INDEX_DROP',

  // Shared Infrastructure
  SHARED_INFRA_START: 'SHARED_INFRA_START',
  SHARED_INFRA_STOP: 'SHARED_INFRA_STOP',
  SHARED_DATABASE_CREATE: 'SHARED_DATABASE_CREATE',
  SHARED_DATABASE_DROP: 'SHARED_DATABASE_DROP',

  // Realtime
  REALTIME_CONFIG_UPDATE: 'REALTIME_CONFIG_UPDATE',

  // Studio
  STUDIO_TENANT_ACTIVATE: 'STUDIO_TENANT_ACTIVATE',
  STUDIO_DEACTIVATE: 'STUDIO_DEACTIVATE',

  // Edge Functions
  FUNCTION_SAVE: 'FUNCTION_SAVE',
  FUNCTION_DELETE: 'FUNCTION_DELETE',
  FUNCTION_DEPLOY: 'FUNCTION_DEPLOY',
  FUNCTION_ENV_UPDATE: 'FUNCTION_ENV_UPDATE',

  // Backup Destinations
  BACKUP_DESTINATION_CREATE: 'BACKUP_DESTINATION_CREATE',
  BACKUP_DESTINATION_UPDATE: 'BACKUP_DESTINATION_UPDATE',
  BACKUP_DESTINATION_DELETE: 'BACKUP_DESTINATION_DELETE',
  BACKUP_DESTINATION_TEST: 'BACKUP_DESTINATION_TEST',

  // Vault (Secrets)
  VAULT_SECRET_CREATE: 'VAULT_SECRET_CREATE',
  VAULT_SECRET_UPDATE: 'VAULT_SECRET_UPDATE',
  VAULT_SECRET_DELETE: 'VAULT_SECRET_DELETE',
  VAULT_SECRET_REVEAL: 'VAULT_SECRET_REVEAL',

  // Security Settings
  SECURITY_SETTING_UPDATE: 'SECURITY_SETTING_UPDATE',

  // Storage Buckets & Files
  STORAGE_BUCKET_CREATE: 'STORAGE_BUCKET_CREATE',
  STORAGE_BUCKET_DELETE: 'STORAGE_BUCKET_DELETE',
  STORAGE_FILE_DELETE: 'STORAGE_FILE_DELETE',
  STORAGE_SIGNED_URL_CREATE: 'STORAGE_SIGNED_URL_CREATE',
  STORAGE_CDN_CACHE_INVALIDATE: 'STORAGE_CDN_CACHE_INVALIDATE',

  // Custom Domains
  DOMAIN_CREATE: 'DOMAIN_CREATE',
  DOMAIN_DELETE: 'DOMAIN_DELETE',
  DOMAIN_SSL_ACTIVATE: 'DOMAIN_SSL_ACTIVATE',
  DOMAIN_SSL_MANUAL: 'DOMAIN_SSL_MANUAL',

  // Webhooks
  WEBHOOK_CREATE: 'WEBHOOK_CREATE',
  WEBHOOK_UPDATE: 'WEBHOOK_UPDATE',
  WEBHOOK_DELETE: 'WEBHOOK_DELETE',

  // Replicas
  REPLICA_CREATE: 'REPLICA_CREATE',
  REPLICA_DELETE: 'REPLICA_DELETE',

  // Queues
  QUEUE_EXTENSION_ENABLE: 'QUEUE_EXTENSION_ENABLE',
  QUEUE_CREATE: 'QUEUE_CREATE',
  QUEUE_DELETE: 'QUEUE_DELETE',
  QUEUE_PURGE: 'QUEUE_PURGE',

  // System & Instance Updates
  INSTANCE_IMAGE_UPDATE: 'INSTANCE_IMAGE_UPDATE',
  INSTANCE_IMAGE_UPDATE_COMPLETED: 'INSTANCE_IMAGE_UPDATE_COMPLETED',
  DOCKER_UPDATE: 'DOCKER_UPDATE',
  DOCKER_UPDATE_COMPLETED: 'DOCKER_UPDATE_COMPLETED',
  POSTGRES_IMAGE_UPDATE: 'POSTGRES_IMAGE_UPDATE',
  MULTIBASE_UPDATE: 'MULTIBASE_UPDATE',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
